function out = print_news_docu(dir_root, year_nowcast, quarter_nowcast)
    dir_nowcast = [dir_root '\Nowcasts\' year_nowcast 'Q' quarter_nowcast] ;
    load([dir_nowcast '\output_mat\results.mat'])

    Nrs = readmatrix('../../../model_specs_Nrs.csv'); % # number of factors
    Nps = readmatrix('../../../model_specs_Nps.csv'); % # of lags in factor VAR
    Njs = readmatrix('../../../model_specs_Njs.csv'); % # of lags in idiosysncratic component

    str_nowcast = [year_nowcast 'Q' quarter_nowcast]; 
    
    if strcmp(quarter_nowcast, '4')
        str_forecast = [ num2str(str2double(year_nowcast) + 1) 'Q1'] ; 
    else 
        str_forecast = [ year_nowcast 'Q' quarter_nowcast] ; 
    end

    addpath('functions')

    vars = fieldnames(results.nowcast);
    Nvintages = length(results.vintages);
    Nmodels = length(Nrs) * length(Nps) * length(Njs);

    % loop over vars
    for k = 1:numel(vars)
        var = vars{k};
        var_long = results.nowcast.(var).varname_long;

        % loop over models
        modcounter = 1;
        for Nr = Nrs
            for Np = Nps
                for Nj = Njs
                    flag_ewpool = 0 ; 
                    threshold = 0.02 ; 

                    % nowcasts
                    savename = ['nowcasts_' var '_' str_nowcast '_Nr' num2str(Nr) '_Np' num2str(Np) '_Nj' num2str(Nj)] ;
                    f_docu_all_vintages(squeeze(results.nowcast.(var).new(1,:,modcounter)), ...
                           results.vintages, ...
                           results.nowcast.(var).details(:,modcounter), ...
                           Nr, ...
                           Np, ...
                           Nj, ...
                           savename, ...
                           var_long, ...
                           flag_ewpool, ...
                           threshold,...
                           dir_nowcast) ;               
    
                    % forecasts
                    savename = ['forecasts_' var '_' str_forecast '_Nr' num2str(Nr) '_Np' num2str(Np) '_Nj' num2str(Nj)] ;
                    f_docu_all_vintages(squeeze(results.forecast.(var).new(1,:,modcounter)), ...
                           results.vintages, ...
                           results.forecast.(var).details(:,modcounter), ...
                           Nr, ...
                           Np, ...
                           Nj, ...
                           savename, ...
                           var_long, ...
                           flag_ewpool, ...
                           threshold, ...
                           dir_nowcast) ; 
   
                    flag_ewpool = 1 ;                         
                        
      
                    ew_pool_details = [] ;
                    
                    for v = 2 : Nvintages
                        temp_forecasts = [] ; 
                        temp_weights = [] ; 
                        temp_impacts = [] ; 
                        for m = 1 : Nmodels
                            temp_forecasts(:,m) = results.nowcast.(var).details(v,m).forecasts ; 
                            temp_weights(:,m) = results.nowcast.(var).details(v,m).weights ;
                            temp_impacts(:,m) = results.nowcast.(var).details(v,m).impacts ;
                            if m == 1
                                ew_pool_details(v,1).varnames = results.nowcast.(var).details(v,m).varnames ; 
                                ew_pool_details(v,1).actuals = results.nowcast.(var).details(v,m).actuals ; 
                            end
                        end
                        ew_pool_details(v,1).forecasts = mean(temp_forecasts,2) ; 
                        ew_pool_details(v,1).weights = mean(temp_weights,2) ; 
                        ew_pool_details(v,1).impacts = mean(temp_impacts,2) ; 
                    end
                    
                    savename = ['nowcasts_' var '_' str_nowcast '_equalweightpool'] ;
                    f_docu_all_vintages(mean(results.nowcast.(var).new(1,:,:),3), ...
                        results.vintages, ...
                        ew_pool_details, ...
                        Nr, ...
                        Np, ...
                        Nj, ...
                        savename, ...
                        var_long, ...
                        flag_ewpool, ...
                        threshold, ...
                        dir_nowcast) ; 
                    f_docu_one_vintage(mean(results.nowcast.(var).new(1,:,:),3), ...
                            results.vintages, ...
                            ew_pool_details, ...
                            Nr, ...
                            Np, ...
                            Nj, ...
                            savename, ...
                            var_long, ...
                            flag_ewpool, ...
                            dir_nowcast)   
                
                    % forecasts
                    ew_pool_details = [] ; 
                    
                    for v = 2 : Nvintages
                        temp_forecasts = [] ; 
                        temp_weights = [] ; 
                        temp_impacts = [] ; 
                        for m = 1 : Nmodels
                            temp_forecasts(:,m) = results.forecast.(var).details(v,m).forecasts ; 
                            temp_weights(:,m) = results.forecast.(var).details(v,m).weights ;
                            temp_impacts(:,m) = results.forecast.(var).details(v,m).impacts ;
                            if m == 1
                                ew_pool_details(v,1).varnames = results.forecast.(var).details(v,m).varnames ; 
                                ew_pool_details(v,1).actuals = results.forecast.(var).details(v,m).actuals ; 
                            end
                        end
                        ew_pool_details(v,1).forecasts = mean(temp_forecasts,2) ; 
                        ew_pool_details(v,1).weights = mean(temp_weights,2) ; 
                        ew_pool_details(v,1).impacts = mean(temp_impacts,2) ; 
                    end
                    
                    savename = ['forecasts_' var '_' str_forecast '_equalweightpool'] ;
                    f_docu_all_vintages(mean(results.forecast.(var).new(1,:,:),3), ...
                        results.vintages, ...
                        ew_pool_details, ...
                        Nr, ...
                        Np, ...
                        Nj, ...
                        savename, ...
                        var_long, ...
                        flag_ewpool, ...
                        threshold,...
                        dir_nowcast) ; 
                    
                    f_docu_one_vintage(mean(results.forecast.(var).new(1,:,:),3), ...
                            results.vintages, ...
                            ew_pool_details, ...
                            Nr, ...
                            Np, ...
                            Nj, ...
                            savename, ...
                            var_long, ...
                            flag_ewpool, ...
                            dir_nowcast)   
                end
            end
        end
    end
    disp('Done printing news to txt!')
    quit(0);
end