function f_table(nowcast,revision,groupcontrib,vintages,savename,groupnames,dirname)

T = table(nowcast', ...
    groupcontrib(1,:)', ...
    groupcontrib(2,:)', ...
    groupcontrib(3,:)', ...
    groupcontrib(4,:)', ...
    groupcontrib(5,:)', ...
    groupcontrib(6,:)', ...
    groupcontrib(7,:)', ...
    groupcontrib(8,:)', ...
    groupcontrib(9,:)', ... % only when using old data with separate ifo and esi categories
    revision',...
    'VariableNames',groupnames,...
    'RowNames',vintages);                     

writetable(T,[dirname '\tables\' savename '.xlsx'],'WriteRowNames',true) 


