function data = f_loadoptions_financialdataBuBa


temp = { 'Umlaufrendite: insgesamt', 'financial' , 2 , 'm' , 1 , 0 , 'BBSIS.M.I.UMR.RD.EUR.A.B.A.A.R.A.A._Z._Z.A'  ; ...
         %'Umlaufrendite: Bankschuldverschreibungen', 'financial' , 2 , 'm' , 1 , 0 , 'BBSIS.M.I.UMR.RD.EUR.S122.B.A.A.R.A.A._Z._Z.A' ; ...
         %'Umlaufrendite: Hypothekenpfandbriefe', 'financial' , 2 , 'm' , 1 , 0 , 'BBSIS.M.I.UMR.RD.EUR.MFISX.B.X100.A.R.A.A._Z._Z.A'  ;  ...
         %'Umlaufrendite: oeffentliche Pfandbriefe', 'financial' , 2 , 'm' , 1 , 0  , 'BBSIS.M.I.UMR.RD.EUR.MFISX.B.A150.A.R.A.A._Z._Z.A' ; ...
         %'Umlaufrendite: Spezialkreditschuldverschreibungen', 'financial' , 2 , 'm' , 1 , 0 , 'BBSIS.M.I.UMR.RD.EUR.MFISP.B.A.A.R.A.A._Z._Z.A' ; ...
         %'Umlaufrendite: Sonstige Bankschuldverschreibungen', 'financial' , 2 , 'm' , 1 , 0 , 'BBSIS.M.I.UMR.RD.EUR.MFISX.B.X401.A.R.A.A._Z._Z.A'; ...
         %'Umlaufrendite: Unternehmensanleihen', 'financial' , 2 , 'm' , 1 , 0 , 'BBSIS.M.I.UMR.RD.EUR.X2000.B.A.A.R.A.A._Z._Z.A' ; ...
         %'Umlaufrendite: Anleihen der oeffentlichen Hand', 'financial' , 2 , 'm' , 1 , 0 , 'BBSIS.M.I.UMR.RD.EUR.S1312.B.A.A.R.A.A._Z._Z.A' ; ...
         %'Umlaufrendite: Anleihen der Bundeslaender', 'financial' , 2 , 'm' , 1 , 0 , 'BBSIS.M.I.UMR.RD.EUR.S13.B.A.A.R.A.A._Z._Z.A' ; ...
         'Zinsstrukturkurve: 0.5 Jahre RLZ', 'financial' , 2 , 'm' , 1 , 0 , 'BBSIS.M.I.ZST.ZI.EUR.S1311.B.A604.R005X.R.A.A._Z._Z.A' ; ...
         'Zinsstrukturkurve: 1 Jahre RLZ', 'financial' , 2 , 'm' , 1 , 0 , 'BBSIS.M.I.ZST.ZI.EUR.S1311.B.A604.R01XX.R.A.A._Z._Z.A' ; ...
         %'Zinsstrukturkurve: 2 Jahre RLZ', 'financial' , 2 , 'm' , 1 , 0 , 'BBSIS.M.I.ZST.ZI.EUR.S1311.B.A604.R02XX.R.A.A._Z._Z.A' ; ...
         %'Zinsstrukturkurve: 3 Jahre RLZ', 'financial' , 2 , 'm' , 1 , 0 , 'BBSIS.M.I.ZST.ZI.EUR.S1311.B.A604.R03XX.R.A.A._Z._Z.A' ; ...
         %'Zinsstrukturkurve: 4 Jahre RLZ', 'financial' , 2 , 'm' , 1 , 0 , 'BBSIS.M.I.ZST.ZI.EUR.S1311.B.A604.R04XX.R.A.A._Z._Z.A' ; ...
         %'Zinsstrukturkurve: 5 Jahre RLZ', 'financial' , 2 , 'm' , 1 , 0 , 'BBSIS.M.I.ZST.ZI.EUR.S1311.B.A604.R05XX.R.A.A._Z._Z.A' ; ...
         %'Zinsstrukturkurve: 6 Jahre RLZ', 'financial' , 2 , 'm' , 1 , 0 , 'BBSIS.M.I.ZST.ZI.EUR.S1311.B.A604.R06XX.R.A.A._Z._Z.A' ; ...
         %'Zinsstrukturkurve: 7 Jahre RLZ', 'financial' , 2 , 'm' , 1 , 0 , 'BBSIS.M.I.ZST.ZI.EUR.S1311.B.A604.R07XX.R.A.A._Z._Z.A' ; ...
         %'Zinsstrukturkurve: 8 Jahre RLZ', 'financial' , 2 , 'm' , 1 , 0 , 'BBSIS.M.I.ZST.ZI.EUR.S1311.B.A604.R08XX.R.A.A._Z._Z.A' ; ...
         %'Zinsstrukturkurve: 9 Jahre RLZ', 'financial' , 2 , 'm' , 1 , 0 , 'BBSIS.M.I.ZST.ZI.EUR.S1311.B.A604.R09XX.R.A.A._Z._Z.A' ; ...
         'Zinsstrukturkurve: 10 Jahre RLZ', 'financial' , 2 , 'm' , 1 , 0 ,'BBSIS.M.I.ZST.ZI.EUR.S1311.B.A604.R10XX.R.A.A._Z._Z.A' ;  ...
         'DAX', 'financial' , 3 , 'm' , 1 , 0 , 'BBQFS.M.DE.CORP.PRICE_DAX._X.0000' ; ...
         %'NEER (EWK 19)', 'financial' , 3 , 'm' , 1 , 0  , 'BBEE1.M.I8.AAA.XZE012.A.AABAN.M00' ; ...
         'NEER (EWK 42)', 'financial' , 3 , 'm' , 1 , 0  , 'BBEE1.M.I8.AAA.XZE022.A.AABAN.M00' } ; 
     
data.names = temp(:,1)' ;         
data.groups= temp(:,2)' ;
data.trafo = cell2mat(temp(:,3)') ; 
data.type = temp(:,4)' ; 
data.flag_usestartvals = cell2mat(temp(:,5)') ; 
data.flag_sa = cell2mat(temp(:,6)') ;
data.seriesnames = temp(:,7)' ; 

























