function data = f_loadoptions_BuBaRTD


temp = {    % - ----------------- PRODUCTION ---------------------------- % 
'Produzierendes Gewerbe ohne Bau' , 'production' , 3 , 'm' , 1 , 0 , 'BBKRT.M.DE.Y.I.IP1.AA020.C.I'; ... 
'Produzierendes Gewerbe' , 'production' , 3 , 'm' , 1 , 0 , 'BBKRT.M.DE.Y.I.IP1.AA021.C.I'; ...
'Baugewerbe' , 'production' , 3 , 'm' , 1 , 0 , 'BBKRT.M.DE.Y.I.IP1.AA030.C.I'; ...
'Bauhauptgewerbe' , 'production' , 3 , 'm' , 1 , 0 , 'BBKRT.M.DE.Y.I.IP1.AA031.C.I'; ...
'Ausbaugewerbe' , 'production' , 3 , 'm' , 1 , 0 , 'BBKRT.M.DE.Y.I.IP1.AA032.C.I'; ...
'Industrie' , 'production' , 3 , 'm' , 1 , 0 , 'BBKRT.M.DE.Y.I.IP1.ACM01.C.I'; ...
'Vorleistungsgueter'  , 'production', 3 , 'm' , 1 , 0 , 'BBKRT.M.DE.Y.I.IP1.ACM02.C.I'; ...
'Investitionsgueter' , 'production' , 3 , 'm' , 1 , 0 , 'BBKRT.M.DE.Y.I.IP1.ACM03.C.I'; ...
'Konsumgueter' , 'production' , 3 , 'm' , 1 , 0 , 'BBKRT.M.DE.Y.I.IP1.ACM04.C.I'; ...
'Gebrauchsgueter' , 'production' , 3 , 'm' , 1 , 0 , 'BBKRT.M.DE.Y.I.IP1.ACM05.C.I'; ...
'Verbrauchsgueter' , 'production' , 3 , 'm' , 1 , 0 , 'BBKRT.M.DE.Y.I.IP1.ACM06.C.I'; ...
'Energie' , 'production' , 3 , 'm' , 1 , 0 , 'BBKRT.M.DE.Y.I.IP1.ACM07.C.I'; ...
'Hochbau' , 'production' , 3 , 'm' , 1 , 0 , 'BBKRT.M.DE.Y.I.IP1.AFC11.C.I'; ...
'Tiefbau' , 'production' , 3 , 'm' , 1 , 0 , 'BBKRT.M.DE.Y.I.IP1.AFC12.C.I'; ...
        % - --------------------- ORDERS -------------------------------- %
'Bauhauptgewerbe' , 'orders' , 3 , 'm' , 1 , 0 , 'BBKRT.M.DE.Y.I.IO1.AA031.C.I' ; ...
'Industrie' , 'orders' , 3 , 'm' , 1 , 0 , 'BBKRT.M.DE.Y.I.IO1.ACM01.C.I' ; ...
'Vorleistungsgueter' , 'orders' , 3 , 'm' , 1 , 0 , 'BBKRT.M.DE.Y.I.IO1.ACM02.C.I'; ...
'Investitionsgueter' , 'orders' , 3 , 'm' , 1 , 0 , 'BBKRT.M.DE.Y.I.IO1.ACM03.C.I'; ...
'Konsumgueter' , 'orders' , 3 , 'm' , 1 , 0 , 'BBKRT.M.DE.Y.I.IO1.ACM04.C.I' ; ...  
'Hochbau' , 'orders' , 3 , 'm' , 1 , 0 , 'BBKRT.M.DE.Y.I.IO1.AFC11.C.I' ; ...
'Tiefbau' , 'orders' , 3 , 'm' , 1 , 0 , 'BBKRT.M.DE.Y.I.IO1.AFC12.C.I' ; ...
'Wohnungsbau' , 'orders' , 3 , 'm' , 1 , 0 , 'BBKRT.M.DE.Y.I.IO1.AFC15.C.I' ; ... 
'Bauhauptgewerbe, gewerbliche Auftraggeber' , 'orders' , 3 , 'm' , 1 , 0 , 'BBKRT.M.DE.Y.I.IO1.AFC21.C.I' ; ...
'Bauhauptgewerbe, oeffentliche Auftraggeber und Stra�enbau' , 'orders' , 3 , 'm' , 1 , 0 , 'BBKRT.M.DE.Y.I.IO1.AFC22.C.I'; ...
'Industrie (Inland)' , 'orders' , 3 , 'm' , 1 , 0 , 'BBKRT.M.DE.Y.I.IO2.ACM01.C.I' ; ...
'Vorleistungsgueter (Inland)' , 'orders' , 3 , 'm' , 1 , 0 , 'BBKRT.M.DE.Y.I.IO2.ACM02.C.I' ; ...
'Investitionsgueter (Inland)' , 'orders' , 3 , 'm' , 1 , 0 , 'BBKRT.M.DE.Y.I.IO2.ACM03.C.I' ; ...
'Konsumgueter (Inland)' , 'orders' , 3 , 'm' , 1 , 0 , 'BBKRT.M.DE.Y.I.IO2.ACM04.C.I' ; ...
'Industrie (Ausland)' , 'orders' , 3 , 'm' , 1 , 0 , 'BBKRT.M.DE.Y.I.IO3.ACM01.C.I' ; ...
'Vorleistungsgueter (Ausland)' , 'orders' , 3 , 'm' , 1 , 0 , 'BBKRT.M.DE.Y.I.IO3.ACM02.C.I' ; 
'Investitionsgueter (Ausland)' , 'orders' , 3 , 'm' , 1 , 0 , 'BBKRT.M.DE.Y.I.IO3.ACM03.C.I' ; 
'Konsumgueter (Ausland)' , 'orders' , 3 , 'm' , 1 , 0 , 'BBKRT.M.DE.Y.I.IO3.ACM04.C.I' ; 
%       % - --------------------- TURNOVER -------------------------------- %
'Bauhauptgewerbe' , 'turnover' , 3 , 'm' , 1 , 0 , 'BBKRT.M.DE.Y.I.IT1.AA031.V.A'; ... 
'Industrie' , 'turnover' , 3 , 'm' , 1 , 0 , 'BBKRT.M.DE.Y.I.IT1.ACM01.V.I'; ...
'Vorleistungsgueter' , 'turnover' , 3 , 'm' , 1 , 0 , 'BBKRT.M.DE.Y.I.IT1.ACM02.V.I'; ...
'Investitionsgueter' , 'turnover' , 3 , 'm' , 1 , 0 , 'BBKRT.M.DE.Y.I.IT1.ACM03.V.I'; ...
'Konsumgueter' , 'turnover' , 3 , 'm' , 1 , 0 , 'BBKRT.M.DE.Y.I.IT1.ACM04.V.I'; ...
'Gebrauchsgueter' , 'turnover' , 3 , 'm' , 1 , 0 , 'BBKRT.M.DE.Y.I.IT1.ACM05.V.I'; ...
'Verbrauchsgueter' , 'turnover' , 3 , 'm' , 1 , 0 , 'BBKRT.M.DE.Y.I.IT1.ACM06.V.I'; ...
'Wohnungsbau' , 'turnover' , 3 , 'm' , 1 , 0 , 'BBKRT.M.DE.Y.I.IT1.AFC15.V.A'; ...
'Bauhauptgewerbe, gewerbliche Auftraggeber' , 'turnover' , 3 , 'm' , 1 , 0 , 'BBKRT.M.DE.Y.I.IT1.AFC21.V.A'; ...
'Bauhauptgewerbe, oeffentliche Auftraggeber und Stra�enbau' , 'turnover' , 3 , 'm' , 1 , 0 , 'BBKRT.M.DE.Y.I.IT1.AFC22.V.A'; ...
'Einzelhandel (ohne KFZ)' , 'turnover' , 3 , 'm' , 1 , 0 , 'BBKRT.M.DE.Y.I.IT1.AGA01.C.I'; ...
'Einzelhandel' , 'turnover' , 3 , 'm' , 1 , 0 , 'BBKRT.M.DE.Y.I.IT1.AGC02.C.I'; ...
'Handel mit KFZ' , 'turnover' , 3 , 'm' , 1 , 0 , 'BBKRT.M.DE.Y.I.IT1.AGD01.C.I'; ...  
'Industrie (Inland)' , 'turnover' , 3 , 'm' , 1 , 0 , 'BBKRT.M.DE.Y.I.IT2.ACM01.V.I'; ...
'Vorleistungsgueter (Inland)' , 'turnover' , 3 , 'm' , 1 , 0 , 'BBKRT.M.DE.Y.I.IT2.ACM02.V.I'; ...
'Investitionsgueter (Inland)' , 'turnover' , 3 , 'm' , 1 , 0 , 'BBKRT.M.DE.Y.I.IT2.ACM03.V.I'; ...
'Konsumgueter (Inland)' , 'turnover' , 3 , 'm' , 1 , 0 , 'BBKRT.M.DE.Y.I.IT2.ACM04.V.I'; ...
'Industrie (Ausland)' , 'turnover' , 3 , 'm' , 1 , 0 , 'BBKRT.M.DE.Y.I.IT3.ACM01.V.I'; ...
'Vorleistungsgueter (Ausland)' , 'turnover' , 3 , 'm' , 1 , 0 , 'BBKRT.M.DE.Y.I.IT3.ACM02.V.I'; ...
'Investitionsgueter (Ausland)' , 'turnover' , 3 , 'm' , 1 , 0 , 'BBKRT.M.DE.Y.I.IT3.ACM03.V.I'; ...
'Konsumgueter (Ausland)' , 'turnover' , 3 , 'm' , 1 , 0 , 'BBKRT.M.DE.Y.I.IT3.ACM04.V.I'; ... 
%       % - --------------------- PRICES -------------------------------- %
'VPI: insgesamt' , 'prices' , 3 , 'm' , 1 , 0 , 'BBKRT.M.DE.Y.P.PC1.PC100.R.I'; ... 
'VPI: insgesamt (ex Energie)' , 'prices' , 3 , 'm' , 1 , 0 , 'BBKRT.M.DE.S.P.PC1.PC110.R.I'; ... 
'VPI: insgesamt (ex Energie und Nahrungsmittel)' , 'prices' , 3 , 'm' , 1 , 0 , 'BBKRT.M.DE.Y.P.PC1.PC120.R.I'; ... 
'VPI: Nahrungsmittel' , 'prices' , 3 , 'm' , 1 , 0 , 'BBKRT.M.DE.S.P.PC1.PC200.R.I'; ... 
'VPI: andere Gebrauchs- und Verbrauchsgueter' , 'prices' , 3 , 'm' , 1 , 0 , 'BBKRT.M.DE.S.P.PC1.PC300.R.I'; ... 
'VPI: Energie' , 'prices' , 3 , 'm' , 1 , 0 , 'BBKRT.M.DE.Y.P.PC1.PC400.R.I'; ... 
'VPI: Dienstleistungen' , 'prices' , 3 , 'm' , 1 , 0 , 'BBKRT.M.DE.Y.P.PC1.PC500.R.I'; ... 
'VPI: Dienstleistungen (ex Mieten)' , 'prices' , 3 , 'm' , 1 , 0 , 'BBKRT.M.DE.Y.P.PC1.PC510.R.I'; ... 
'VPI: Mieten' , 'prices' , 3 , 'm' , 1 , 0 , 'BBKRT.M.DE.S.P.PC1.PC600.R.I'; ... 
'VPI: Mieten (ex Nebenkosten)' , 'prices' , 3 , 'm' , 1 , 0 , 'BBKRT.M.DE.S.P.PC1.PC610.R.I'; ... 
'PPI: industrielle Produkte' , 'prices' , 3 , 'm' , 1 , 0 , 'BBKRT.M.DE.S.P.PP1.PP100.R.I'; ...
'PPI: industrielle Produkte (ex Energie)' , 'prices' , 3 , 'm' , 1 , 0 , 'BBKRT.M.DE.S.P.PP1.PP200.R.I'; ...
'PPI: landwirtschaftliche Produkte' , 'prices' , 3 , 'm' , 1 , 0 , 'BBKRT.M.DE.S.P.PP1.PP400.R.I'; ...
'Exportpreise' , 'prices' , 3 , 'm' , 1 , 0 , 'BBKRT.M.DE.S.P.CX1.PP000.R.I'; ...
'Importpreise' , 'prices' , 3 , 'm' , 1 , 0 , 'BBKRT.M.DE.S.P.CM1.PP000.R.I'; ...  
      % - ------------------- LABOR MARKET ------------------------------ %
'Erwerbstaetige: Verarbeitendes Gewerbe und Bergbau' , 'labor market' , 3 , 'm' , 1 , 0 , 'BBKRT.M.DE.S.L.BE1.AA022.P.I'; ... 
%'Erwerbstaetige: Bauhauptgewerbe' , 'labor market' , 3 , 'm' , 1 , 0 , 'BBKRT.M.DE.S.L.BE1.AA031.P.A'; ...
'Erwerbstaetige: Gesamtwirtschaft' , 'labor market' , 3 , 'm' , 1 , 0 , 'BBKRT.M.DE.S.L.BE1.CA010.P.A'; ...
'Erwerbstaetigenstunden: Verarbeitendes Gewerbe und Bergbau' , 'labor market' , 3 , 'm' , 1 , 0 , 'BBKRT.M.DE.Y.L.BE2.AA022.H.I'; ... 
'Erwerbstaetigenstunden: Bauhauptgewerbe' , 'labor market' , 3 , 'm' , 1 , 0 , 'BBKRT.M.DE.Y.L.BE2.AA031.H.A'; ...
'Sozialversichungspflichtig Beschaeftigte' , 'labor market' , 3 , 'm' , 1 , 0 , 'BBKRT.M.DE.S.L.BG1.CA010.P.A'; ...
'BLG: Verarbeitendes Gewerbe und Bergbau' , 'labor market' , 3 , 'm' , 1 , 0 , 'BBKRT.M.DE.Y.L.DE2.AA022.V.I'; ... 
'BLG: Bauhauptgewerbe' , 'labor market' , 3 , 'm' , 1 , 0 , 'BBKRT.M.DE.Y.L.DE2.AA031.V.A'; ...  
      % - ------------------- NATIONAL ACCOUNTS ------------------------------ % 
'gross domestic product' , 'national accounts' , 3 , 'q:E' , 0 , 0 , 'BBKRT.Q.DE.Y.A.AG1.CA010.A.I';...
'private consumption (nominal)' , 'national accounts' , 3 , 'q:E' , 0 , 0  , 'BBKRT.Q.DE.Y.A.CA1.BA100.V.A';...
'private consumption' , 'national accounts' , 3 , 'q:E' , 0 , 0  , 'BBKRT.Q.DE.Y.A.CA1.BA100.A.I';...
'public consumption' , 'national accounts' , 3 , 'q:E' , 0 , 0  , 'BBKRT.Q.DE.Y.A.CA1.BA200.A.I';...
'public consumption (nominal)' , 'national accounts' , 3 , 'q:E' , 0 , 0  , 'BBKRT.Q.DE.Y.A.CA1.BA200.V.A';...             
'gross fixed capital formation' , 'national accounts' , 3 , 'q:E' , 0 , 0  , 'BBKRT.Q.DE.Y.A.CD1.CA010.A.I';...
'gross fixed capital formation (nominal)' , 'national accounts' , 3 , 'q:E' , 0 , 0  , 'BBKRT.Q.DE.Y.A.CD1.CA010.V.A';...
'imports' , 'national accounts' , 3 , 'q:E' , 0 , 0  , 'BBKRT.Q.DE.Y.A.CM1.CA010.A.I';...
'imports (nominal)' , 'national accounts' , 3 , 'q:E' , 0 , 0  , 'BBKRT.Q.DE.Y.A.CM1.CA010.V.A';...       
'exports' , 'national accounts' , 3 , 'q:E' , 0 , 0  , 'BBKRT.Q.DE.Y.A.CX1.CA010.A.I';...
'exports (nominal)' , 'national accounts' , 3 , 'q:E' , 0 , 0  , 'BBKRT.Q.DE.Y.A.CX1.CA010.V.A';...
'inventories (contr. to growth)' , 'national accounts' , 1 , 'q:E' , 0 , 0  , 'BBKRT.Q.DE.Y.A.CJ1.CA010.A.G';...
} ;

data.names = temp(:,1)' ;         
data.groups= temp(:,2)' ;
data.trafo = cell2mat(temp(:,3)') ; 
data.type = temp(:,4)' ; 
data.flag_usestartvals = cell2mat(temp(:,5)') ; 
data.flag_sa = cell2mat(temp(:,6)') ;
data.seriesnames = temp(:,7)' ; 

























































